# -*- coding: utf-8 -*-
"""2311cs020528.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejnA7PsiZJtOlS6LOzSBzFj4c65iNyUK
"""

import pandas as pd
screen_time = [2,4,5]
sleep_hours = [3,4,6]
stu_name = ["abhiram", "teju", "abhi"]
dict1 = {
    "screen_time":screen_time,
    "sleep_hours":sleep_hours,
    "stu_name":stu_name

}
print(dict1)
df = pd.DataFrame(dict1)
print(df)